language: generic
jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11.4 # OS X 10.14.6
    - os: osx
      osx_image: xcode10.2 # OS X 10.14
    - os: osx
      osx_image: xcode9.4  # OS X 10.13
script:
  - ./test/run.sh
